products = [
    {"id": 1, "name": "Laptop", "price": 999.99, "quantity": 50, "category": "Computers"},
    {"id": 2, "name": "Smartphone", "price": 699.99, "quantity": 200, "category": "Mobile Devices"},
    {"id": 3, "name": "Tablet", "price": 499.99, "quantity": 100, "category": "Mobile Devices"},
    {"id": 4, "name": "Smartwatch", "price": 199.99, "quantity": 150, "category": "Wearables"},
    {"id": 5, "name": "Headphones", "price": 89.99, "quantity": 300, "category": "Audio"},
    {"id": 6, "name": "Bluetooth Speaker", "price": 49.99, "quantity": 250, "category": "Audio"},
    {"id": 7, "name": "Gaming Console", "price": 399.99, "quantity": 75, "category": "Gaming"},
    {"id": 8, "name": "Keyboard", "price": 29.99, "quantity": 150, "category": "Accessories"},
    {"id": 9, "name": "Mouse", "price": 19.99, "quantity": 150, "category": "Accessories"},
    {"id": 10, "name": "Monitor", "price": 149.99, "quantity": 60, "category": "Displays"},
    {"id": 11, "name": "External Hard Drive", "price": 89.99, "quantity": 100, "category": "Storage"},
    {"id": 12, "name": "SSD Drive", "price": 79.99, "quantity": 120, "category": "Storage"},
    {"id": 13, "name": "Router", "price": 49.99, "quantity": 85, "category": "Networking"},
    {"id": 14, "name": "Power Bank", "price": 29.99, "quantity": 200, "category": "Accessories"},
    {"id": 15, "name": "Drone", "price": 299.99, "quantity": 25, "category": "Gadgets"},
    {"id": 16, "name": "Camera", "price": 499.99, "quantity": 40, "category": "Photography"},
    {"id": 17, "name": "Tripod", "price": 39.99, "quantity": 80, "category": "Photography"},
    {"id": 18, "name": "Fitness Tracker", "price": 129.99, "quantity": 120, "category": "Wearables"},
    {"id": 19, "name": "TV", "price": 899.99, "quantity": 30, "category": "Home Entertainment"},
    {"id": 20, "name": "Soundbar", "price": 179.99, "quantity": 50, "category": "Home Entertainment"},
]